### ISSUE TITLE
Change Path and Domain of the Cookie

### ISSUE THREAD

**Issue by obrunodelgado** [contently/xdomain-cookies#14]
Hello, first of all thank you for developing this library and helping us with this issue.

I'm currently setting and getting the cookie without any technical problems, but the cookie is setted with the path '/trackercookie' (where it's hosted) and the domain is being setted to 'api.qas.impresa.pt'. But I need it to be setted with the path **'/'** and the domain to **'.impresa.pt'**, because I want this cookie to be sent to the micro services hosted at api.impresa.pt and id.impresa.pt. 

I tried to change the method _set_local_cookie, adding 'path=/' to the string at line 109, but it didn't work for me.

Is it possible to manipulate this values inside xdomain_cookie.html?

**Comment by obrunodelgado** [comment]
![screenshot from 2018-10-18 13-07-17](https://user-images.githubusercontent.com/2372140/47153205-d0a35700-d2d6-11e8-911d-c05f235898c7.png)

**Comment by yanniboi** [comment]
+1

**Comment by yanniboi** [comment]
Similarly we have the cookies being set for www.domain.com and would like to be able to set them for domain.com.
