### ISSUE TITLE
Vulnerabilities Found

### ISSUE THREAD

**Issue by mpbunch** [contently/xdomain-cookies#15]
git clone ...
npm install

added 521 packages from 916 contributors and audited 2027 packages in 15.095s
**found 13 vulnerabilities** (4 low, 1 moderate, **6 high**, 2 critical)

npm audit fix
**fixed 0 of 13 vulnerabilities** in 2027 scanned packages
  4 package updates for 13 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

**Comment by trinaldi** [comment]
That must be in part due a known [Gulp issue](https://github.com/gulpjs/gulp/issues/2201)
