### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adibPlaybuzz** [contently/xdomain-cookies#5]
Hi, 
can you please set the license of the project?

Thanks

**Comment by yshaool** [comment]
The license is standard Creative Commons, as specified in the package.json here: https://github.com/contently/xdomain-cookies/blob/master/package.json#L15

**Comment by audenaert** [comment]
Please see https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software 

An MIT license would probably be more appropriate. Also, the inclusion of a LICENSE.md or similar file would be helpful.

(BTW: Thanks for the work and documentation on this)
